### ISSUE TITLE
Laptop Screen isnt scale properly.

### ISSUE THREAD

**Issue by kxmpxtxnt** [korvahannu/arch-nvidia-drivers-installation-guide#23]
Hey 👋🏼. 
Im very grateful for guides like yours.
But since installing the nvidia drivers i cant scale my laptop screen without change the scale off all screens.
This is a little bit annoying because my laptop screen is relative HighDPI on 14" and anything is really small. Do you know any fix or workaround for this?

Paul :)

**Comment by Dwyriel** [comment]
Might be irrelevant here but, I had similar problems on my AMD+NVIDIA laptop when I was explicitly changing the "display mode" in bios to be dedicated gpu only rather than the default "Optimus" (using both dedicated nvidia gpu + integrated amd gpu). Have you perhaps done something similar? (Also if you could, provide more info about your system and what software you're running)
